/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApiApplyRouteImport } from './routes/api/apply'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiLedgerRouteImport } from './routes/api/ledger'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApplyRoute = ApiApplyRouteImport.update({
  id: '/api/apply',
  path: '/api/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLedgerRoute = ApiLedgerRouteImport.update({
  id: '/api/ledger',
  path: '/api/ledger',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/api/apply': typeof ApiApplyRoute
  '/api/contact': typeof ApiContactRoute
  '/api/ledger': typeof ApiLedgerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/api/apply': typeof ApiApplyRoute
  '/api/contact': typeof ApiContactRoute
  '/api/ledger': typeof ApiLedgerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/api/apply': typeof ApiApplyRoute
  '/api/contact': typeof ApiContactRoute
  '/api/ledger': typeof ApiLedgerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/apply' | '/contact' | '/api/apply' | '/api/contact' | '/api/ledger'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/apply' | '/contact' | '/api/apply' | '/api/contact' | '/api/ledger'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/contact'
    | '/api/apply'
    | '/api/contact'
    | '/api/ledger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  ContactRoute: typeof ContactRoute
  ApiApplyRoute: typeof ApiApplyRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiLedgerRoute: typeof ApiLedgerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apply': {
      id: '/api/apply'
      path: '/api/apply'
      fullPath: '/api/apply'
      preLoaderRoute: typeof ApiApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ledger': {
      id: '/api/ledger'
      path: '/api/ledger'
      fullPath: '/api/ledger'
      preLoaderRoute: typeof ApiLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  ContactRoute: ContactRoute,
  ApiApplyRoute: ApiApplyRoute,
  ApiContactRoute: ApiContactRoute,
  ApiLedgerRoute: ApiLedgerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
